version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    image: miscellany-fe:0.0.7
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - /app/node_modules
      - .:/app
    command: npm run start
