version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    image: miscellany-be:0.0.1
    ports:
      - '5001:5001'
    env_file:
      - .env
    command: npm run start:prod
