version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: ${NODE_ENV}
    image: miscellany-be:0.0.4
    ports:
      - '5001:5001'
    env_file:
      - .env # 기본적으로 프로덕션 환경 사용
    environment:
      NODE_ENV: ${NODE_ENV} # 실행 시 환경 변수 전달
      HOST: 0.0.0.0
    volumes:
      - /app/node_modules
      - .:/app # 개발환경에서는 소스 코드 실시간 반영
    #command: npm run start:prod
    command: >
      sh -c "if [ ${NODE_ENV} = 'development' ]; then npm run dev; else npm run start:prod; fi"
