version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    image: miscellany-be:0.0.7
    ports:
      - '5001:5001'
    env_file:
      - .env # 기본적으로 프로덕션 환경 사용
    command: npm run start:prod
    # timezone 설정
    environment:
      - TZ=Asia/Seoul
    volumes:
      - /app/node_modules
      - .:/app
