name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-backend:

    runs-on: ubuntu-latest
    name: Build Frontend Docker Image
    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: |
        cd backend
        docker build . --file Dockerfile --tag miscellany-bot_be:$(date +%s)
